spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yourDB
    password:
    username:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    banner-mode: off
